name: Generate ASCII Art

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-ascii:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Cowsay Program
      run: sudo apt-get install -y cowsay

    - name: Execute Cowsay Program
      run: |
        cowsay -f dragon "Run for cover, I am a dragon!" >> dragon.txt

    - name: Upload dragon.txt
      uses: actions/upload-artifact@v3
      with:
        name: dragon-file
        path: dragon.txt

  test-and-read:
    runs-on: ubuntu-latest
    needs: generate-ascii

    steps:
    - name: Download dragon.txt
      uses: actions/download-artifact@v3
      with:
        name: dragon-file

    - name: Test File exists
      run: |
        grep -i "dragon" dragon.txt || echo "Dragon not found in file!"

    - name: Read file
      run: cat dragon.txt

    - name: Checkout Repo Files
      run: ls